default_install_hook_types: [pre-commit, pre-merge-commit, post-merge]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-toml
      - id: check-yaml
        args: ['--unsafe']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-fmt
        name: ruff format
        language: python
        types: [python]
        entry: ruff format

      - id: ruff-lint
        name: ruff linting
        language: python
        types: [python]
        entry: ruff check
        # Respect `exclude` and `extend-exclude` settings.
        args: ["--force-exclude"]
