default_install_hook_types: [pre-commit, pre-merge-commit, post-merge]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-toml
      - id: check-yaml
        args: ['--unsafe']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        types: [python]
        entry: black

      - id: ruff
        name: ruff
        language: python
        types: [python]
        entry: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args: ["--force-exclude"]
