name: Code formatting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-fmt:
    name: ruff-fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the commit that triggered the workflow
        uses: actions/checkout@v3.5.3

      - name: Load environment from YAML
        uses: dcarbone/yaml-to-env-action@v2.1.1
        with:
          yaml-file: .env-dev.yaml

      - name: Setup python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install code formatting dependencies
        run: pip install -e ".[formatter]"

      - name: Run ruff formatting check
        run: ruff format --check
