name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-python:
    uses: ./.github/workflows/setup-python-env.yml
    with:
      pythonEnvPath: '.env.dev'

  lint:
    name: ruff
    runs-on: ubuntu-latest
    needs: setup-python
    steps:
      - name: Checkout the commit that triggered the workflow
        uses: actions/checkout@v3.5.3

      - name: Install linting dependencies
        run: pip install ".[lint]"

      - name: Run Ruff
        run: ruff check
