name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruff-lint:
    name: ruff-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the commit that triggered the workflow
        uses: actions/checkout@v3.5.3

      - name: Load environment from YAML
        uses: dcarbone/yaml-to-env-action@v2.1.1
        with:
          yaml-file: .env-dev.yaml

      - name: Setup python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install linting dependencies
        run: pip install -e ".[lint]"

      - name: Run Ruff
        run: ruff check
